package org.uva.jomi.ql.tests.utilities;

import java.util.List;

import org.uva.jomi.ql.ast.analysis.TypeResolver;
import org.uva.jomi.ql.ast.statements.Stmt;

public class TypeResolverTestGenerator {
	
	private final String[] testSources;
	private TypeResolver typeResolver;
	private int testNumber = 1;
	
	public TypeResolverTestGenerator(String[] testStrings) {
		this.testSources = testStrings;
		this.typeResolver = new TypeResolver(false);
	}
	
	public void generateTypeResolverTests() {
		for (String testSource : testSources) {
			List<Stmt> ast = TestUtilities.buildAst(testSource);
			typeResolver.resolve(ast);
			System.out.format("	String generatedSource%d = \"%s\";\n\n", testNumber, testSource.replaceAll("\"", "\\\\\""));
			
			
			System.out.format("	@Test\n	public void generatedTest%d() throws Exception {\n", testNumber);
			System.out.format("		List<Stmt> ast = TestUtilities.buildAst(generatedSource%d);\n", testNumber);
			System.out.format("		typeResolver.resolve(ast);\n");
			System.out.format("		assertTrue(typeResolver.getNumberOfErrors() == %d);\n", typeResolver.getNumberOfErrors());
			for (int idx = 0; idx < typeResolver.getNumberOfErrors(); idx++) {
				System.out.format("		assertTrue(typeResolver.\n");
				System.out.format("			getErrorAtIndex(%d).equals(\"%s\"));\n", idx, typeResolver.getErrorAtIndex(idx));
			}
			System.out.println("	}\n");
			testNumber++;
		}
	}
	
	
	public static void main(String[] args) {
		//String[] testSources = { "form Form1 {\"\" q0: boolean \"string\" != \"string\"}" };
		String[] testSources = { "form Form1 {\"\" q0: string 1 + 1}",
				"form Form1 {\"\" q0: string 1 + true}",
				"form Form1 {\"\" q0: string 1 + \"string\"}",
				"form Form1 {\"\" q0: string true + true}",
				"form Form1 {\"\" q0: string true + \"string\"}",
				"form Form1 {\"\" q0: string \"string\" + \"string\"}",
				"form Form1 {\"\" q0: string 1 - 1}",
				"form Form1 {\"\" q0: string 1 - true}",
				"form Form1 {\"\" q0: string 1 - \"string\"}",
				"form Form1 {\"\" q0: string true - true}",
				"form Form1 {\"\" q0: string true - \"string\"}",
				"form Form1 {\"\" q0: string \"string\" - \"string\"}",
				"form Form1 {\"\" q0: string 1 * 1}",
				"form Form1 {\"\" q0: string 1 * true}",
				"form Form1 {\"\" q0: string 1 * \"string\"}",
				"form Form1 {\"\" q0: string true * true}",
				"form Form1 {\"\" q0: string true * \"string\"}",
				"form Form1 {\"\" q0: string \"string\" * \"string\"}",
				"form Form1 {\"\" q0: string 1 / 1}",
				"form Form1 {\"\" q0: string 1 / true}",
				"form Form1 {\"\" q0: string 1 / \"string\"}",
				"form Form1 {\"\" q0: string true / true}",
				"form Form1 {\"\" q0: string true / \"string\"}",
				"form Form1 {\"\" q0: string \"string\" / \"string\"}",
				"form Form1 {\"\" q0: string 1 && 1}",
				"form Form1 {\"\" q0: string 1 && true}",
				"form Form1 {\"\" q0: string 1 && \"string\"}",
				"form Form1 {\"\" q0: string true && true}",
				"form Form1 {\"\" q0: string true && \"string\"}",
				"form Form1 {\"\" q0: string \"string\" && \"string\"}",
				"form Form1 {\"\" q0: string 1 || 1}",
				"form Form1 {\"\" q0: string 1 || true}",
				"form Form1 {\"\" q0: string 1 || \"string\"}",
				"form Form1 {\"\" q0: string true || true}",
				"form Form1 {\"\" q0: string true || \"string\"}",
				"form Form1 {\"\" q0: string \"string\" || \"string\"}",
				"form Form1 {\"\" q0: string 1 > 1}",
				"form Form1 {\"\" q0: string 1 > true}",
				"form Form1 {\"\" q0: string 1 > \"string\"}",
				"form Form1 {\"\" q0: string true > true}",
				"form Form1 {\"\" q0: string true > \"string\"}",
				"form Form1 {\"\" q0: string \"string\" > \"string\"}",
				"form Form1 {\"\" q0: string 1 >= 1}",
				"form Form1 {\"\" q0: string 1 >= true}",
				"form Form1 {\"\" q0: string 1 >= \"string\"}",
				"form Form1 {\"\" q0: string true >= true}",
				"form Form1 {\"\" q0: string true >= \"string\"}",
				"form Form1 {\"\" q0: string \"string\" >= \"string\"}",
				"form Form1 {\"\" q0: string 1 < 1}",
				"form Form1 {\"\" q0: string 1 < true}",
				"form Form1 {\"\" q0: string 1 < \"string\"}",
				"form Form1 {\"\" q0: string true < true}",
				"form Form1 {\"\" q0: string true < \"string\"}",
				"form Form1 {\"\" q0: string \"string\" < \"string\"}",
				"form Form1 {\"\" q0: string 1 <= 1}",
				"form Form1 {\"\" q0: string 1 <= true}",
				"form Form1 {\"\" q0: string 1 <= \"string\"}",
				"form Form1 {\"\" q0: string true <= true}",
				"form Form1 {\"\" q0: string true <= \"string\"}",
				"form Form1 {\"\" q0: string \"string\" <= \"string\"}",
				"form Form1 {\"\" q0: string 1 == 1}",
				"form Form1 {\"\" q0: string 1 == true}",
				"form Form1 {\"\" q0: string 1 == \"string\"}",
				"form Form1 {\"\" q0: string true == true}",
				"form Form1 {\"\" q0: string true == \"string\"}",
				"form Form1 {\"\" q0: string \"string\" == \"string\"}",
				"form Form1 {\"\" q0: string 1 != 1}",
				"form Form1 {\"\" q0: string 1 != true}",
				"form Form1 {\"\" q0: string 1 != \"string\"}",
				"form Form1 {\"\" q0: string true != true}",
				"form Form1 {\"\" q0: string true != \"string\"}",
				"form Form1 {\"\" q0: string \"string\" != \"string\"}",
				"form Form1 {\"\" q0: integer 1 + 1}",
				"form Form1 {\"\" q0: integer 1 + true}",
				"form Form1 {\"\" q0: integer 1 + \"string\"}",
				"form Form1 {\"\" q0: integer true + true}",
				"form Form1 {\"\" q0: integer true + \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" + \"string\"}",
				"form Form1 {\"\" q0: integer 1 - 1}",
				"form Form1 {\"\" q0: integer 1 - true}",
				"form Form1 {\"\" q0: integer 1 - \"string\"}",
				"form Form1 {\"\" q0: integer true - true}",
				"form Form1 {\"\" q0: integer true - \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" - \"string\"}",
				"form Form1 {\"\" q0: integer 1 * 1}",
				"form Form1 {\"\" q0: integer 1 * true}",
				"form Form1 {\"\" q0: integer 1 * \"string\"}",
				"form Form1 {\"\" q0: integer true * true}",
				"form Form1 {\"\" q0: integer true * \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" * \"string\"}",
				"form Form1 {\"\" q0: integer 1 / 1}",
				"form Form1 {\"\" q0: integer 1 / true}",
				"form Form1 {\"\" q0: integer 1 / \"string\"}",
				"form Form1 {\"\" q0: integer true / true}",
				"form Form1 {\"\" q0: integer true / \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" / \"string\"}",
				"form Form1 {\"\" q0: integer 1 && 1}",
				"form Form1 {\"\" q0: integer 1 && true}",
				"form Form1 {\"\" q0: integer 1 && \"string\"}",
				"form Form1 {\"\" q0: integer true && true}",
				"form Form1 {\"\" q0: integer true && \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" && \"string\"}",
				"form Form1 {\"\" q0: integer 1 || 1}",
				"form Form1 {\"\" q0: integer 1 || true}",
				"form Form1 {\"\" q0: integer 1 || \"string\"}",
				"form Form1 {\"\" q0: integer true || true}",
				"form Form1 {\"\" q0: integer true || \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" || \"string\"}",
				"form Form1 {\"\" q0: integer 1 > 1}",
				"form Form1 {\"\" q0: integer 1 > true}",
				"form Form1 {\"\" q0: integer 1 > \"string\"}",
				"form Form1 {\"\" q0: integer true > true}",
				"form Form1 {\"\" q0: integer true > \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" > \"string\"}",
				"form Form1 {\"\" q0: integer 1 >= 1}",
				"form Form1 {\"\" q0: integer 1 >= true}",
				"form Form1 {\"\" q0: integer 1 >= \"string\"}",
				"form Form1 {\"\" q0: integer true >= true}",
				"form Form1 {\"\" q0: integer true >= \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" >= \"string\"}",
				"form Form1 {\"\" q0: integer 1 < 1}",
				"form Form1 {\"\" q0: integer 1 < true}",
				"form Form1 {\"\" q0: integer 1 < \"string\"}",
				"form Form1 {\"\" q0: integer true < true}",
				"form Form1 {\"\" q0: integer true < \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" < \"string\"}",
				"form Form1 {\"\" q0: integer 1 <= 1}",
				"form Form1 {\"\" q0: integer 1 <= true}",
				"form Form1 {\"\" q0: integer 1 <= \"string\"}",
				"form Form1 {\"\" q0: integer true <= true}",
				"form Form1 {\"\" q0: integer true <= \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" <= \"string\"}",
				"form Form1 {\"\" q0: integer 1 == 1}",
				"form Form1 {\"\" q0: integer 1 == true}",
				"form Form1 {\"\" q0: integer 1 == \"string\"}",
				"form Form1 {\"\" q0: integer true == true}",
				"form Form1 {\"\" q0: integer true == \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" == \"string\"}",
				"form Form1 {\"\" q0: integer 1 != 1}",
				"form Form1 {\"\" q0: integer 1 != true}",
				"form Form1 {\"\" q0: integer 1 != \"string\"}",
				"form Form1 {\"\" q0: integer true != true}",
				"form Form1 {\"\" q0: integer true != \"string\"}",
				"form Form1 {\"\" q0: integer \"string\" != \"string\"}",
				"form Form1 {\"\" q0: boolean 1 + 1}",
				"form Form1 {\"\" q0: boolean 1 + true}",
				"form Form1 {\"\" q0: boolean 1 + \"string\"}",
				"form Form1 {\"\" q0: boolean true + true}",
				"form Form1 {\"\" q0: boolean true + \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" + \"string\"}",
				"form Form1 {\"\" q0: boolean 1 - 1}",
				"form Form1 {\"\" q0: boolean 1 - true}",
				"form Form1 {\"\" q0: boolean 1 - \"string\"}",
				"form Form1 {\"\" q0: boolean true - true}",
				"form Form1 {\"\" q0: boolean true - \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" - \"string\"}",
				"form Form1 {\"\" q0: boolean 1 * 1}",
				"form Form1 {\"\" q0: boolean 1 * true}",
				"form Form1 {\"\" q0: boolean 1 * \"string\"}",
				"form Form1 {\"\" q0: boolean true * true}",
				"form Form1 {\"\" q0: boolean true * \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" * \"string\"}",
				"form Form1 {\"\" q0: boolean 1 / 1}",
				"form Form1 {\"\" q0: boolean 1 / true}",
				"form Form1 {\"\" q0: boolean 1 / \"string\"}",
				"form Form1 {\"\" q0: boolean true / true}",
				"form Form1 {\"\" q0: boolean true / \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" / \"string\"}",
				"form Form1 {\"\" q0: boolean 1 && 1}",
				"form Form1 {\"\" q0: boolean 1 && true}",
				"form Form1 {\"\" q0: boolean 1 && \"string\"}",
				"form Form1 {\"\" q0: boolean true && true}",
				"form Form1 {\"\" q0: boolean true && \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" && \"string\"}",
				"form Form1 {\"\" q0: boolean 1 || 1}",
				"form Form1 {\"\" q0: boolean 1 || true}",
				"form Form1 {\"\" q0: boolean 1 || \"string\"}",
				"form Form1 {\"\" q0: boolean true || true}",
				"form Form1 {\"\" q0: boolean true || \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" || \"string\"}",
				"form Form1 {\"\" q0: boolean 1 > 1}",
				"form Form1 {\"\" q0: boolean 1 > true}",
				"form Form1 {\"\" q0: boolean 1 > \"string\"}",
				"form Form1 {\"\" q0: boolean true > true}",
				"form Form1 {\"\" q0: boolean true > \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" > \"string\"}",
				"form Form1 {\"\" q0: boolean 1 >= 1}",
				"form Form1 {\"\" q0: boolean 1 >= true}",
				"form Form1 {\"\" q0: boolean 1 >= \"string\"}",
				"form Form1 {\"\" q0: boolean true >= true}",
				"form Form1 {\"\" q0: boolean true >= \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" >= \"string\"}",
				"form Form1 {\"\" q0: boolean 1 < 1}",
				"form Form1 {\"\" q0: boolean 1 < true}",
				"form Form1 {\"\" q0: boolean 1 < \"string\"}",
				"form Form1 {\"\" q0: boolean true < true}",
				"form Form1 {\"\" q0: boolean true < \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" < \"string\"}",
				"form Form1 {\"\" q0: boolean 1 <= 1}",
				"form Form1 {\"\" q0: boolean 1 <= true}",
				"form Form1 {\"\" q0: boolean 1 <= \"string\"}",
				"form Form1 {\"\" q0: boolean true <= true}",
				"form Form1 {\"\" q0: boolean true <= \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" <= \"string\"}",
				"form Form1 {\"\" q0: boolean 1 == 1}",
				"form Form1 {\"\" q0: boolean 1 == true}",
				"form Form1 {\"\" q0: boolean 1 == \"string\"}",
				"form Form1 {\"\" q0: boolean true == true}",
				"form Form1 {\"\" q0: boolean true == \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" == \"string\"}",
				"form Form1 {\"\" q0: boolean 1 != 1}",
				"form Form1 {\"\" q0: boolean 1 != true}",
				"form Form1 {\"\" q0: boolean 1 != \"string\"}",
				"form Form1 {\"\" q0: boolean true != true}",
				"form Form1 {\"\" q0: boolean true != \"string\"}",
				"form Form1 {\"\" q0: boolean \"string\" != \"string\"}" };
		
		TypeResolverTestGenerator testGenerator = new TypeResolverTestGenerator(testSources);
		testGenerator.generateTypeResolverTests();
		
	}

}
