/*
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.qls.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.uva.sc.pc.qls.QSLangRuntimeModule
import org.uva.sc.pc.qls.QSLangStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class QSLangIdeSetup extends QSLangStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new QSLangRuntimeModule, new QSLangIdeModule))
	}
	
}
