/*
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql.validation

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class QLangValidator extends AbstractQLangValidator {

	public static val INVALID_NAME = 'invalidName'
	public static val INVALID_TYPES = 'invalidName'

//	@Check
//	def checkGreetingStartsWithCapital(Form form) {
//		if (!Character.isUpperCase(form.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					QLangPackage.Literals.FORM__NAME,
//					INVALID_NAME)
//		}
//	}
}
