/**
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql;

import org.uva.sc.pc.ql.QLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class QLangStandaloneSetup extends QLangStandaloneSetupGenerated {
  public static void doSetup() {
    new QLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
