/**
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql;

import org.uva.sc.pc.ql.AbstractQLangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class QLangRuntimeModule extends AbstractQLangRuntimeModule {
}
