/*
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQLangScopeProvider extends DelegatingScopeProvider {
}
