/*
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/uva/sc/pc/ql/parser/antlr/internal/InternalQLang.tokens");
	}
}
