/**
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.uva.sc.pc.ql.ui.AbstractQLangUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class QLangUiModule extends AbstractQLangUiModule {
  public QLangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
