/**
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql.validation;

import org.uva.sc.pc.ql.validation.AbstractQLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class QLangValidator extends AbstractQLangValidator {
}
