/**
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.uva.sc.pc.ql.QLangRuntimeModule;
import org.uva.sc.pc.ql.QLangStandaloneSetup;
import org.uva.sc.pc.ql.ide.QLangIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class QLangIdeSetup extends QLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    QLangRuntimeModule _qLangRuntimeModule = new QLangRuntimeModule();
    QLangIdeModule _qLangIdeModule = new QLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_qLangRuntimeModule, _qLangIdeModule));
  }
}
