/**
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql.ide;

import org.uva.sc.pc.ql.ide.AbstractQLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class QLangIdeModule extends AbstractQLangIdeModule {
}
