/*
 * generated by Xtext 2.12.0
 */
package org.uva.sc.pc.ql.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractQLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.uva.sc.pc.ql.qLang.QLangPackage.eINSTANCE);
		return result;
	}
	
}
